"""
drift_detection.py
--------------------
Deliverable 7: Input drift detection.

Compares the distribution of the training data (reference) against the
100-row generated dataset used for prediction in Deliverable 5.

Method:
  - Numeric features:      two-sample Kolmogorov-Smirnov test
  - Categorical features:  Chi-square test of independence on value
                            counts (with Cramer's V as an effect size)

A feature is flagged as "drifted" if its test p-value < alpha (default
0.05). Since the 100-row set in this assignment is synthetically
generated by uniform sampling over the training min/max range (see
generate_predictions.py), some drift is EXPECTED and is a useful
sanity check that the test is working, not necessarily a production
concern -- this is called out in the printed summary.

Usage:
    python -m observability.drift_detection \
        --reference model/train_reference.csv \
        --current observability/sample_100.csv \
        --out observability/drift_report.json
"""

import argparse
import json

import pandas as pd
from scipy.stats import chi2_contingency, ks_2samp

NUMERIC = ["age", "trestbps", "chol", "thalach", "oldpeak"]
CATEGORICAL = ["gender", "cp", "fbs", "restecg", "exang", "slope", "ca", "thal"]


def normalize_gender(series: pd.Series) -> pd.Series:
    if series.dtype == object:
        return series.map({"male": 1, "female": 0}).fillna(series)
    return series


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference", default="model/train_reference.csv")
    parser.add_argument("--current", default="observability/sample_100.csv")
    parser.add_argument("--out", default="observability/drift_report.json")
    parser.add_argument("--alpha", type=float, default=0.05)
    args = parser.parse_args()

    ref = pd.read_csv(args.reference)
    cur = pd.read_csv(args.current)
    ref["gender"] = normalize_gender(ref["gender"])
    cur["gender"] = normalize_gender(cur["gender"])

    report = {"alpha": args.alpha, "numeric_features": {}, "categorical_features": {}}
    drifted = []

    for col in NUMERIC:
        stat, p = ks_2samp(ref[col].dropna(), cur[col].dropna())
        is_drift = bool(p < args.alpha)
        report["numeric_features"][col] = {
            "test": "ks_2samp", "statistic": float(stat), "p_value": float(p),
            "drift_detected": is_drift,
        }
        if is_drift:
            drifted.append(col)

    for col in CATEGORICAL:
        ref_counts = ref[col].value_counts()
        cur_counts = cur[col].value_counts()
        categories = sorted(set(ref_counts.index) | set(cur_counts.index))
        table = pd.DataFrame({
            "reference": [ref_counts.get(c, 0) for c in categories],
            "current": [cur_counts.get(c, 0) for c in categories],
        }, index=categories)
        # avoid zero-row/col chi-square errors on tiny/sparse samples
        table = table.loc[table.sum(axis=1) > 0]
        if table.shape[0] < 2:
            report["categorical_features"][col] = {"test": "chi2", "note": "insufficient categories"}
            continue
        stat, p, dof, _ = chi2_contingency(table.T + 1e-9)
        is_drift = bool(p < args.alpha)
        report["categorical_features"][col] = {
            "test": "chi2_contingency", "statistic": float(stat), "p_value": float(p),
            "drift_detected": is_drift,
        }
        if is_drift:
            drifted.append(col)

    report["summary"] = {
        "drifted_features": drifted,
        "n_drifted": len(drifted),
        "n_features_checked": len(NUMERIC) + len(CATEGORICAL),
        "interpretation": (
            "Features flagged here differ significantly between the "
            "training distribution and the 100-row generated set. Because "
            "the 100-row set is generated by uniform sampling over the "
            "training min/max range (not resampling the training "
            "distribution itself), moderate drift on skewed features is "
            "expected and demonstrates the detector is sensitive; a real "
            "production drift alert would compare against genuinely new "
            "incoming traffic instead."
        ),
    }

    with open(args.out, "w") as f:
        json.dump(report, f, indent=2)

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()